config:
  dotpath: .
  link_dotfile_default: relative
  link_on_import: relative
dotfiles:
  d_tealdeer:
    src: tealdeer
    dst: ~/.config/tealdeer
  f_user-dirs.dirs:
    src: user-dirs.dirs
    dst: ~/.config/user-dirs.dirs
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_xbindkeysrc:
    src: xbindkeysrc
    dst: ~/.xbindkeysrc
  d_bin:
    src: bin
    dst: ~/bin
  f_redshift.conf:
    src: redshift.conf
    dst: ~/.config/redshift.conf
  d_ranger:
    src: ranger
    dst: ~/.config/ranger
  f_picom.conf:
    src: picom.conf
    dst: ~/.config/picom.conf
  d_nvim:
    src: nvim
    dst: ~/.config/nvim
  d_mpv:
    src: mpv
    dst: ~/.config/mpv
  d_lsd:
    src: lsd
    dst: ~/.config/lsd
  d_kitty:
    src: kitty
    dst: ~/.config/kitty
  f_imwheelrc:
    src: imwheelrc
    dst: ~/.imwheelrc
  f_gpg.conf:
    src: gnupg/gpg.conf
    dst: ~/.gnupg/gpg.conf
  d_flashfocus:
    src: flashfocus
    dst: ~/.config/flashfocus
  f_bashrc:
    src: bash/bashrc
    dst: ~/.bashrc
  f_aliases:
    src: bash/aliases
    dst: ~/.aliases
  f_bash_profile:
    src: bash/bash_profile
    dst: ~/.bash_profile
  d_alacritty:
    src: alacritty
    dst: ~/.config/alacritty
profiles:
  work-laptop:
    dotfiles:
    - f_bashrc
    - f_aliases
    - d_nvim
    - d_lsd
    - d_alacritty
  linux-pc:
    dotfiles:
    - d_tealdeer
    - f_user-dirs.dirs
    - f_xinitrc
    - f_xbindkeysrc
    - d_bin
    - f_redshift.conf
    - d_ranger
    - f_picom.conf
    - d_nvim
    - d_mpv
    - d_lsd
    - d_kitty
    - f_imwheelrc
    - f_gpg.conf
    - d_flashfocus
    - f_bashrc
    - f_aliases
    - f_bash_profile
    - d_alacritty
  samsung-laptop:
    dotfiles:
    - d_tealdeer
    - f_user-dirs.dirs
    - f_xinitrc
    - f_xbindkeysrc
    - d_bin
    - f_redshift.conf
    - d_ranger
    - f_picom.conf
    - d_nvim
    - d_mpv
    - d_lsd
    - d_kitty
    - f_imwheelrc
    - f_gpg.conf
    - d_flashfocus
    - f_bashrc
    - f_aliases
    - f_bash_profile
    - d_alacritty
