#! /bin/sh

export QT_QPA_PLATFORMTHEME=qt5ct

pgrep -x sxhkd > /dev/null || sxhkd &

~/bin/polybar-start &

xbindkeys

# Disable automatic screen saving
xset -dpms

DISPLAY=":0" xset r rate 230 50

xsetroot -cursor_name left_ptr

# copyq &
clipcatd

nm-applet &

easyeffects --gapplication-service &

picom -b

blueman-applet &

DO_NOT_UNSET_QT_QPA_PLATFORMTHEME=1 DO_NOT_SET_DESKTOP_SETTINGS_UNAWARE=1 megasync &

xss-lock xsecurelock &


# wallpaper
feh --bg-fill ~/Pictures/Pretty/1475101751132.jpg

# allows dragging windows in 240hz
bspc config pointer_motion_interval 3

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

[ -f ~/bin/fixfilepicker ] && ~/bin/fixfilepicker &

# ~/.config/bspwm/focused-border.sh &

dunst &

eww daemon

# BEGIN pc
 #bspc monitor $MONITOR2 -d 1 2
 #bspc monitor $MONITOR1 -d 3 4 5 6 7 8
 #bspc desktop '^1' -l monocle
 #bspc desktop '^3' -l monocle
# END pc
# BEGIN work-laptop
#if xrandr | grep -q "HDMI-1 connected"; then
#    bspc monitor $MONITOR1 -d 8 9 10
#    bspc monitor $MONITOR2 -d 1 2 3 4 5 6 7
#    bspc desktop '^1' -l monocle
#    bspc desktop '^8' -l monocle
#else
#    bspc monitor $MONITOR1 -d 1 2 3 4 5 6 7 8
#    bspc desktop '^1' -l monocle
#fi
# END work-laptop

bspc config border_width         3
bspc config window_gap           10

bspc config normal_border_color  "#3D271E"
bspc config focused_border_color "#8E5A45"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config click_to_focus       any

# bspc rule -a firefox desktop='^5'
# bspc rule -a mpv state=floating
bspc rule -a copyq state=floating
bspc rule -a zenity state=floating
bspc rule -a megasync state=floating
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# bspc rule -a Nemo opacity=false

