#! /bin/sh

export QT_QPA_PLATFORMTHEME=qt5ct
# BEGIN pc
 #export MONITOR1=DP-1
 #export MONITOR2=DP-2
# END pc
# BEGIN work-laptop
#export MONITOR1=eDP-1
# END work-laptop

pgrep -x sxhkd > /dev/null || sxhkd &

~/bin/polybar-start &

nitrogen --restore &

xbindkeys

# Disable automatic screen saving
xset -dpms

DISPLAY=":0" xset r rate 230 50

xsetroot -cursor_name left_ptr

# copyq &
clipcatd

nm-applet &

easyeffects --gapplication-service &

picom -b

blueman-applet &

xss-lock xsecurelock &

# xrandr --output DisplayPort-0 --mode 1920x1080 --rate 240 --right-of DisplayPort-1
# BEGIN pc
 #xrandr --newmode "1920x1080_280v" 628.00 1920 1968 2028 2040 1080 1090 1092 1100 -HSync +Vsync
 #xrandr --addmode $MONITOR1 "1920x1080_280v"
 #xrandr --output $MONITOR1 --right-of $MONITOR2
 #xrandr --output $MONITOR1 --mode 1920x1080_280v --rate 280 --right-of $MONITOR2
# END pc

# allows dragging windows in 240hz
bspc config pointer_motion_interval 3

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

[ -f ~/bin/fixfilepicker ] && ~/bin/fixfilepicker &

# ~/.config/bspwm/focused-border.sh &

dunst &

eww daemon

# BEGIN pc
 #bspc monitor $MONITOR2 -d 1 2
 #bspc monitor $MONITOR1 -d 3 4 5 6 7 8
# END pc
# BEGIN work-laptop
#bspc monitor $MONITOR1 -d 1 2 3 4 5 6 7 8
# END work-laptop

bspc desktop '^1' -l monocle
bspc desktop '^3' -l monocle

bspc config border_width         3
bspc config window_gap           10

bspc config normal_border_color  "#3D271E"
bspc config focused_border_color "#8E5A45"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config click_to_focus       any

# bspc rule -a firefox desktop='^5'
# bspc rule -a mpv state=floating
bspc rule -a copyq state=floating
bspc rule -a zenity state=floating
bspc rule -a megasync state=floating
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# bspc rule -a Nemo opacity=false

