vim.g.mapleader = ' '
-- empty string mappings work like :map, so normal, visual, operator pending (e.g. after d in normal), select (useless, ignore)
vim.keymap.set('',  '<Space>',    '<Nop>')
vim.keymap.set('n', '<A-j>',      ':m .+1<CR>==')
vim.keymap.set('n', '<A-k>',      ':m .-2<CR>==')
vim.keymap.set('v', '<A-j>',      ":m '>+1<CR>gv=gv")
vim.keymap.set('v', '<A-k>',      ":m '<-2<CR>gv=gv")
vim.keymap.set('n', '<A-x>',      ':CccPick<CR>')
vim.keymap.set('v', 'p',          '"_dP')
vim.keymap.set('v', '<',          '<gv')
vim.keymap.set('v', '>',          '>gv')
vim.keymap.set('n', '<C-Up>',     ':resize +2<CR>')
vim.keymap.set('n', '<C-Down>',   ':resize -2<CR>')
vim.keymap.set('n', '<C-Left>',   ':vertical resize -2<CR>')
vim.keymap.set('n', '<C-Right>',  ':vertical resize +2<CR>')
vim.keymap.set('n', '<C-n>',      ':Neotree<CR>')
vim.keymap.set('n', '<C-S-n>',    ':Neotree toggle<CR>')
vim.keymap.set('n', '<Leader>c',  'gcc', { remap = true }) -- this should probably be a plug mapping
vim.keymap.set('v', '<Leader>c',  'gc', { remap = true }) -- this should probably be a plug mapping
vim.keymap.set('n', '<Leader>b',  'gbc', { remap = true }) -- this should probably be a plug mapping
vim.keymap.set('v', '<Leader>b',  'gb', { remap = true }) -- this should probably be a plug mapping
vim.keymap.set('',  '<Leader>d',  '"_d')
vim.keymap.set('',  '<Leader>D',  '"_D')
vim.keymap.set('',  '<Leader>x',  '"_x')
vim.keymap.set('',  '<Leader>X',  '"_X')
vim.keymap.set('',  '<Leader>h',  ':nohlsearch<CR>')
vim.keymap.set('',  '<Leader>r',  ':luafile %<CR>')
vim.keymap.set('',  '<Leader>R',  ':luafile ~/.config/nvim/lua/plugins.lua<CR>:PackerSync<CR>')
vim.keymap.set('',  '<Leader>w',  ':w<CR>')
vim.keymap.set('',  '<Leader>s',  ':SymbolsOutline<CR>')
vim.keymap.set('',  'J',          '4j')
vim.keymap.set('',  'K',          '4k')
vim.keymap.set('',  '+',          '"+y')
vim.keymap.set('',  '<C-h>',      ':BufferPrevious<CR>')
vim.keymap.set('',  '<C-S-h>',    ':BufferMovePrevious<CR>')
vim.keymap.set('',  '<C-j>',      ':join<CR>')
vim.keymap.set('',  '<C-l>',      ':BufferNext<CR>')
vim.keymap.set('',  '<C-S-l>',    ':BufferMoveNext<CR>')
-- vim.keymap.set('',  '<C-q>',      ':bp<bar>sp<bar>bn<bar>bd<CR>')
vim.keymap.set('',  '<C-q>',      ':BufferClose<CR>')
vim.keymap.set('',  '<C-1>',      ':BufferGoto 1<CR>')
vim.keymap.set('',  '<C-2>',      ':BufferGoto 2<CR>')
vim.keymap.set('',  '<C-3>',      ':BufferGoto 3<CR>')
vim.keymap.set('',  '<C-4>',      ':BufferGoto 4<CR>')
vim.keymap.set('',  '<C-5>',      ':BufferGoto 5<CR>')
vim.keymap.set('',  '<C-6>',      ':BufferGoto 6<CR>')
vim.keymap.set('',  '<C-7>',      ':BufferGoto 7<CR>')
vim.keymap.set('',  '<C-8>',      ':BufferGoto 8<CR>')
vim.keymap.set('',  '<C-9>',      ':BufferGoto 9<CR>')
vim.keymap.set('',  '<C-0>',      ':BufferGoto 10<CR>')
vim.keymap.set('n', '<leader>gs', ':Neotree git_status<CR>')
-- vim.keymap.set('n', '<Tab>',     ':lua require("ufo").peekFoldedLinesUnderCursor()<CR>')

-- TELESCOPE
builtin = require('telescope.builtin')
vim.keymap.set('',  '<C-p>',      builtin.find_files)
vim.keymap.set('',  '<C-S-p>',    builtin.live_grep)
vim.keymap.set('n', '<Leader>fh', builtin.help_tags) --'<cmd>Telescope help_tags<cr>')
vim.keymap.set('n', '<Leader>fc', builtin.colorscheme)
vim.keymap.set('n', '<Leader>fr', builtin.lsp_references)
-- vim.keymap.set('n', '<Leader>fs', builtin.lsp_document_symbols)
vim.keymap.set('n', '<Leader>fs', builtin.treesitter)
vim.keymap.set('n', '<Leader>fl', builtin.diagnostics)
-- vim.keymap.set('n', '<Leader>fa', builtin.lsp_code_actions)
-- git
vim.keymap.set('n', '<Leader>gc', builtin.git_bcommits)
vim.keymap.set('n', '<Leader>gb', builtin.git_branches)
vim.keymap.set('n', 'gs',         builtin.git_status)
vim.keymap.set('n', '<Leader>gt', builtin.git_stash)

-- LSP
vim.keymap.set('n', '<leader>a',  ':lua vim.lsp.buf.code_action()<CR>')
vim.keymap.set('',  '<leader>=',  ':lua vim.lsp.buf.format()<CR>')
vim.keymap.set('n', '<C-K>',      ':lua vim.lsp.buf.hover()<CR>')
vim.keymap.set('i', '<C-L>',      ':lua vim.lsp.buf.signature_help()<CR>')
vim.keymap.set('n', '<F2>',       ':lua vim.lsp.buf.rename()<CR>')
vim.keymap.set('n', 'gr',         ':lua vim.lsp.buf.references()<CR>')
vim.keymap.set('n', 'gd',         ':lua vim.lsp.buf.definition()<CR>')
vim.keymap.set('n', 'gD',         ':lua vim.lsp.buf.declaration()<CR>')
vim.keymap.set('n', 'gl',         ':lua vim.diagnostic.open_float()<CR>')
vim.keymap.set('n', '[d',         ':lua vim.diagnostic.goto_prev()<CR>')
vim.keymap.set('n', ']d',         ':lua vim.diagnostic.goto_next()<CR>')

-- vim.keymap.set('n', 'gi', ':lua vim.lsp.buf.implementation()<CR>')
-- vim.keymap.set('', '<leader>fs', ':lua vim.lsp.buf.document_symbol()<CR>')
-- "<leader>qf" vim.diagnostic.setqflist
-- "<leader>q"  vim.diagnostic.setloclist
-- "<leader>fS" vim.lsp.buf.workspace_symbol
